import { AppConfigActions } from "../types";

export const appConfigActions: AppConfigActions = {
  SET_CHARACTERS: "SET_CHARACTERS",
  SET_FILTERED_CHARACTERS: "SET_FILTERED_CHARACTERS",
  SET_DETAIL_CHARACTER: "SET_DETAIL_CHARACTER",
  SET_COMICS: "SET_COMICS",
  SET_FAV_CHARACTERS: "SET_FAV_CHARACTERS",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_SEARCH_VALUE: "SET_SEARCH_VALUE"
};
